### ISSUE TITLE
Idea: Integrate assume_role call into alppaca

### ISSUE THREAD

**Issue by schlomo** [ImmobilienScout24/alppaca#14]
Background: As a user I want to get temporary credentials from an IAM role in a different AWS account than the one used for afp. One option would be to extend my own code to always do an assume_role call before using the credentials given by alppaca. The other option (this issue) would be to extend alppaca to do this for me as a convenience feature. The benefit would be that all applications on my server will use the same remote IAM role and that I don't have to modify all my applications to work in the target AWS account.

Implementation idea: Add a plugin/filter within alppaca that sits between the "get credentials from afp" part and the "store credentials in memory" part. That filter would simply make the assume_role call. Input are temporary credentials and output are also temporary credentials. If it fails then there is no output and the existing alppaca code should retry the operation.

The following drawings illustrate the idea:
![2015-09-25 15 10 53](https://cloud.githubusercontent.com/assets/101384/10102901/5b52cb68-63a1-11e5-9f20-6850595da824.jpg)
![2015-09-25 15 11 04](https://cloud.githubusercontent.com/assets/101384/10102907/65e00c80-63a1-11e5-8378-df9ade5ea5b5.jpg)

Test users: @heroldus

**Comment by heroldus** [comment]
Any news on this issue?

**Comment by esc** [comment]
@heroldus no progress has been made so far.

**Comment by heroldus** [comment]
Done today!
