### ISSUE TITLE
Make alppaca survive setting the clock back when DST is over

### ISSUE THREAD

**Issue by range** [ImmobilienScout24/alppaca#22]
Setting back the clock (as happens when Daylight Saving Time is over) leads to loss of valid credentials in alpacca. It's not sure if that also happens when the clock steps into the other direction, but I'd think that in this case we'll lose the "one second promise", as alppaca needs to fetch current credentials because it probably doesn't have cached credentials which are still valid.

**Comment by esc** [comment]
I have already looked at the code and have some ideas what might constitute a fix, please ask me when you have allocated time for fixing this.

**Comment by schlomo** [comment]
Should we write tests for this scenario? To make sure that we will never break this again? Since "natural" testing occurs only twice a year it might be worth to have a unit test / system test for this.

**Comment by esc** [comment]
Don't ask if we should, but rather how. :-)

On 29 October 2015 14:49:15 CET, Schlomo Schapiro notifications@github.com wrote:

> Should we write tests for this scenario? To make sure that we will
> never break this again? Since "natural" testing occurs only twice a
> year it might be worth to have a unit test / system test for this.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ImmobilienScout24/alppaca/issues/22#issuecomment-152184200

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by esc** [comment]
See also: #23

**Comment by range** [comment]
TODO: Fix with lower priority.

**Comment by snordhausen** [comment]
Alppaca now survives switches from summer to winter time and the other way around.

Testing that is a manual process, because it turned out that "sudo date...." is the best/only way to reproduce the problem. To run the tests, remove the "@skip" decorators in delaytrigger_tests.py.
